### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [17]:
import numpy as np
a=np.random.randint(1,10,(5,5))
print(a)
a[[0,4]]=a[[4,0]]
a

[[5 6 8 2 4]
 [5 3 8 4 4]
 [4 4 7 4 2]
 [9 2 5 6 4]
 [3 2 3 8 6]]


array([[3, 2, 3, 8, 6],
       [5, 3, 8, 4, 4],
       [4, 4, 7, 4, 2],
       [9, 2, 5, 6, 4],
       [5, 6, 8, 2, 4]])

In [7]:
a=3
b=4
a,b=b,a
print(a,b)

4 3


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [24]:
a=np.random.randint(0,10,(5,5))
print(a,"\n")
for i in range(5):
  for j in a:
    if j==0:
      a.remove(i)
print(a)

[[3 5 3 7 5]
 [7 6 4 6 2]
 [0 0 9 7 9]
 [5 7 3 0 5]
 [5 4 8 5 6]] 



ValueError: ignored

### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [25]:
a=np.array([1.00000000+0j , 0.70710678+0.70710678j])
real=[]
img=[]
for i in a:
  if i%2 ==

array([1.        +0.j        , 0.70710678+0.70710678j])

### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [26]:
a=np.array([10,10,20,20,30,30])
np.unique(a)

array([10, 20, 30])

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [29]:
a=np.random.rand(3,3,3)
a

array([[[0.60496024, 0.08843994, 0.27269125],
        [0.66927783, 0.60679335, 0.14418553],
        [0.45279154, 0.11028147, 0.30211847]],

       [[0.79986256, 0.4107972 , 0.76068498],
        [0.5696944 , 0.07411639, 0.80684976],
        [0.20932521, 0.21851986, 0.38506409]],

       [[0.65067184, 0.34530233, 0.701339  ],
        [0.22540205, 0.57221139, 0.41921245],
        [0.30396926, 0.20036891, 0.33746712]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [46]:
a=np.random.randint(0,3,2)
print(a)
b=np.random.randint(0,3,2)
print(b)
print(np.allclose(a,b))

[1 1]
[2 1]
False


### Question 8

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [61]:
a=np.array([[10 ,40],[30 ,20]])
print(np.sort(a,axis=0),"\n")
print(np.sort(a,axis=1),"\n")
print(np.sort(a,axis=None))

[[10 20]
 [30 40]] 

[[10 40]
 [20 30]] 

[10 20 30 40]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [65]:
a=np.array([-1.6 ,-1.5, -0.3 ,0.1 ,1.4 ,1.8, 2. ])
print(np.floor(a))
print(np.ceil(a))

[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [69]:
print(np.arange('2017-03','2017-04',dtype='datetime64[D]'))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [76]:
arr=np.zeros(24)
a=np.arange('2023-06-23','2023-06-24',dtype='datetime64[h]')
print(a)
for i in range(len(arr)):
  for j in a:
    arr[i]=j
print("after adding in array: \n ",arr)

['2023-06-23T00' '2023-06-23T01' '2023-06-23T02' '2023-06-23T03'
 '2023-06-23T04' '2023-06-23T05' '2023-06-23T06' '2023-06-23T07'
 '2023-06-23T08' '2023-06-23T09' '2023-06-23T10' '2023-06-23T11'
 '2023-06-23T12' '2023-06-23T13' '2023-06-23T14' '2023-06-23T15'
 '2023-06-23T16' '2023-06-23T17' '2023-06-23T18' '2023-06-23T19'
 '2023-06-23T20' '2023-06-23T21' '2023-06-23T22' '2023-06-23T23']
after adding in array: 
  [468767. 468767. 468767. 468767. 468767. 468767. 468767. 468767. 468767.
 468767. 468767. 468767. 468767. 468767. 468767. 468767. 468767. 468767.
 468767. 468767. 468767. 468767. 468767. 468767.]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [85]:
a=np.array(['Python', 'PHP'])
b=np.array([' Java' ,' C++'])
print(np.char.add(a,b))

['Python Java' 'PHP C++']
